services:
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - education_net
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - education_net
    volumes:
      - redis:/var/lib/redis/data

  edu:
    container_name: edu
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      REDIS_ADDRESS: redis:6379
      MIGRATION_URL: file://migration
    ports:
      - "1213:1213"
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - education_net
    command: [ "./main" ]


volumes:
  db_data:
  redis:

networks:
  education_net:
    name: education_net
    driver: bridge
