services:
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - edu_net
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - edu_net
    volumes:
      - redis:/var/lib/redis/data

  edu:
    container_name: edu
    build: .
    env_file:
      - .env
    environment:
      GIN_MODE: release
      DB_HOST: postgres
      REDIS_ADDRESS: redis:6379
      MIGRATION_URL: file://migration
    ports:
      - "1213:1213"
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - edu_net
    command: [ "./main" ]


volumes:
  db_data:
    external: true
  redis:
    external: true

networks:
  edu_net:
    name: edu_net
    driver: bridge
    external: true  # Используем существующую сеть
