// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	Title     string
	Text      string
	Comments  []int32
	// from_user nil = пользователь удалён
	FromUsers  []string
	Evaluation pgtype.Int4
}

type Comment struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	Text      string
	// from_user nil = пользователь удалён
	FromUser   pgtype.Text
	Evaluation pgtype.Int4
	Edited     pgtype.Bool
}

type User struct {
	ID          int32
	CreatedAt   pgtype.Timestamptz
	Name        string
	Description pgtype.Text
	Email       pgtype.Text
	Karma       pgtype.Int4
}
