// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	IDArticle  int32
	CreatedAt  pgtype.Timestamptz
	EditedAt   pgtype.Timestamptz
	Title      string
	Text       string
	Comments   []int32
	Authors    []int32
	Evaluation int32
}

type Comment struct {
	IDComment  int32
	CreatedAt  pgtype.Timestamptz
	EditedAt   pgtype.Timestamptz
	Text       string
	FromUser   int32
	Evaluation int32
}

type User struct {
	IDUser      int32
	CreatedAt   pgtype.Timestamptz
	Name        string
	Description string
	Karma       int32
}
