# Просто набор инструкций как и в каком порядке развёртывать приложение на Github Actions
name: Education

on:
  # Или коммит или пул реквест
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          # Изменяются в настройках репозитория во вкладке "Secrets and variables"
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 6s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.4'

    - name: Run Postgres
      run: |
        sudo make net
        sudo make postgres
        sudo apt install postgresql
        sudo service postgresql restart

    - name: Install Golang migrate and sqlc
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/migrate
        docker run --rm -v $(pwd):/src -w /src kjconroy/sqlc generate

    - name: Create database
      run: |
        sudo make createdb 
        sudo make migrateup

    # Тут нельзя использовать make test, т.к. в make test вызывается sqlc, который хрен установишь
    - name: Testing
      run: sudo go test -cover ./...

    - name: Run app in container
      run: |
        sudo make myimage
        sudo make runimage