# Просто набор инструкций как и в каком порядке развёртывать приложение на Github Actions
name: Education

on:
  # Или коммит или пул реквест
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install_and_deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          # Изменяются в настройках репозитория во вкладке "Secrets and variables"
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 6s
          --health-retries 5

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.4'

    - name: Install Golang-migrate and sqlc
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/migrate
        docker run --rm -v .:/src -w /src kjconroy/sqlc generate

    - name: Run Postgres
      run: |
        make net
        make postgres

    - name: Create database
      run: |
        sudo service postgresql restart
        make createdb
        make migrateup

    # Тут нельзя использовать make test, т.к. в make test вызывается sqlc, который сюда хрен установишь
    # ./... тоже нельзя использовать
    # "-short" Пропускаем тесты, которые не выполнятся в Github Actions (типа проверка email)
    - name: Testing
      run: go test -short ./db/sqlc ./tools ./token ./api_gin ./api ./worker
