# Просто набор инструкций как и в каком порядке развёртывать приложение на Github Actions
name: Education

on:
  # Или коммит или пул реквест
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          # Изменяются в настройках репозитория во вкладке "Secrets and variables"
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: education
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 6s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run Docker
      run: |
        sudo docker ps -a
        sudo make postgres
        sudo apt install postgresql
        sudo service postgresql restart

    # Сначала устанавливаем migrate а потом уже вызываем миграции
    - name: Install Golang migrate and sqlc
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/migrate
        docker run --rm -v $(pwd):/src -w /src kjconroy/sqlc generate

    - name: Create database
      run: |
        sudo make createdb 
        sudo make migrateup

    - name: Testing
      run: sudo go test -cover ./db/sqlc
